service: final-challenge

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "*"

functions:
  master-products:
    handler: functions/master-products.handler
    timeout: 30
    events:
      - http:
          path: products
          method: post
          cors: true
  master-people:
    handler: functions/master-people.handler
    timeout: 30
    events:
      - http:
          path: people
          method: post
          cors: true
  master-mysql-store:
    handler: functions/mysql/index.handler
    timeout: 30
    events:
      - http:
          path: store
          method: get
          cors: true